apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: argocd-operator
  annotations:
    description: Template to deploy the Argo CD operator on OCP.
    tags: argocd,gitops,operator
    iconClass: icon-git
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: ${OPERATOR_NAMESPACE}
      annotations:
        openshift.io/description: "This project contains all the resources related to the operator for ArgoCD"
        openshift.io/display-name: "Argo CD"
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: argocd
      namespace: ${OPERATOR_NAMESPACE}
    spec:
      targetNamespaces:
        - ${OPERATOR_NAMESPACE}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: argocd-operator
      namespace: ${OPERATOR_NAMESPACE}
    spec:
      channel: alpha
      installPlanApproval: Automatic 
      name: argocd-operator
      source: community-operators
      sourceNamespace: openshift-marketplace
      # startingCSV: argocd-operator.v0.0.15
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "argocd"