apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pipelines-operator
  annotations:
    description: Template to deploy a Red Hat Openshift Pipelines operator on OCP.
    tags: tekton,pipelines,operator
    iconClass: icon-git
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: openshift-pipelines-operator-rh
      namespace: ${OPERATOR_NAMESPACE}
    spec:
      channel: stable
      installPlanApproval: Automatic
      name: openshift-pipelines-operator-rh
      source: redhat-operators
      sourceNamespace: openshift-marketplace
parameters:
- name: OPERATOR_NAMESPACE
  description: "The project where the operator will be installed."
  required: false
  value: "openshift-operators"